name: Build Common Components Library

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: bump library version
      run: |
        cd projects/input-components
        npm version patch
        cd ../../
        ls -l
    - name: Install Yarn
      uses: borales/actions-yarn@master
    - name: npm install, build, and test
      run: |
        yarn install
        npm i -g @angular/cli
        ng b input-components
        ng test input-components
      env:
        CI: true
