name: Build Common Components Library

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: bump library version
      run: |
        cd projects/input-components
        npm version patch
    - name: npm install, build, and test
      run: |
        npm install
        ng b input-components
        ng test input-component
      env:
        CI: true
