name: Release Management

on:
  push:
    branches:
      - master

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Yarn
        uses: borales/actions-yarn@master
      - name: Publish to npm
        run: |
          yarn install
          npm i -g @angular/cli
          ng b input-components
          ls -l
          cd dist/input-components
          npm version patch
          npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}



